---
- hosts: all
  tasks: 
    - ping: ~

      #ansible-playbook   ansible/playbook.yml -i  ansible/hosts.ini


- hosts: vb
  tasks: 
    - command: "/bin/echo 'inside play #2'"
    - name: Update APT Package Manager repositories cache
      become: true
      apt:
          update_cache: yes

    - name: Update Installed packages
      become: true
      apt:
          upgrade: dist
          #upgrade: safe
          
    - name: Install Git VCS
      become: true
      apt:
          name: git
          state: latest

    - name: Install Nginx web server
      become: true
      apt:
          name: nginx
          state: latest

    - name: Install MySQL DB server
      become: true
      apt:
          name: mysql-server
          state: latest


    - name: Install PHP 7 PPA repository
      become: true
      apt_repository:
          repo: "ppa:ondrej/php"

          #- name: Install PHP 7 CLI
          #become: true
          #apt:
          #repo: "php7.1-cli"
          #state: latest
          
    - name: Install PHP packages
      become: true
      apt:
          name: "{{ item }}"
          state: latest
      with_items:
          - php-cli
          - php-curl
          - php-fpm
          - php-intl
          - php-mysql
          - php-redis
          - php-memcache
          - php-apcu
          - php-xdebug

    - name: Set date.timezone for CLI
      become: true
      lineinfile:
          dest: /etc/php/7.3/cli/php.ini
          regexp: "timezone = "
          line: "date.timezone = PRC"

    - name: Set date.timezone for FPM
      become: true
      lineinfile:
          dest: /etc/php/7.3/fpm/php.ini
          regexp: "timezone = "
          line: "date.timezone = PRC"


- hosts: vb
  tasks: 
    - name: Install cowsay - it's probably important
      apt:
          name: cowsay
      become: true
      #become: yes

